### ISSUE TITLE
Translate this shit!!Plzzz! 

### ISSUE THREAD

**Issue by Armoken** [Frexenus/BSUIR_labs#1]
string q7 = "Who lives in the deep of the ocean";
            string q7v1 = "spongebob";
            string q7v2 = "patric";
            string q7v3 = "Squidward";
            string q7v4 = "plankton";
            string q7v5 = "Mr. Crubs";
            int q7d = 9;

**Comment by Frexenus** [comment]
you don't understant methods of  transparent programming
